version: '3.3'

services: 
  db:
    image: mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mysql_blog
      MYSQL_USER: wp-blog
      MYSQL_PASSWORD: blog-pass

  wordpress:
    container_name: 'wp-blog-theming'
    depends_on: 
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp-blog
      WORDPRESS_DB_PASSWORD: blog-pass
      WORDPRESS_DB_NAME: mysql_blog
    volumes:
      - "./wordpress:/var/www/html"
  
volumes:
  db_data: {}
